# Requests for tag: dependabot



### List Dependabot alerts for an enterprise [GET]
GET {{$dotenv BASE_URL}}/enterprises/{{$dotenv ENTERPRISE_NAME}}/dependabot/alerts
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Lists the repositories Dependabot can access in an organization [GET]
GET {{$dotenv BASE_URL}}/organizations/{{$dotenv ORG_NAME}}/dependabot/repository-access?page={{$dotenv PAGE}}&per_page={{$dotenv PER_PAGE}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Updates Dependabot's repository access list for an organization [PATCH]
PATCH {{$dotenv BASE_URL}}/organizations/{{$dotenv ORG_NAME}}/dependabot/repository-access
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### Set the default repository access level for Dependabot [PUT]
PUT {{$dotenv BASE_URL}}/organizations/{{$dotenv ORG_NAME}}/dependabot/repository-access/default-level
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### List Dependabot alerts for an organization [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/alerts
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List organization secrets [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get an organization public key [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/public-key
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get an organization secret [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Create or update an organization secret [PUT]
PUT {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### Delete an organization secret [DELETE]
DELETE {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List selected repositories for an organization secret [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}/repositories
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Set selected repositories for an organization secret [PUT]
PUT {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}/repositories
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### Add selected repository to an organization secret [PUT]
PUT {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}/repositories/{{$dotenv REPOSITORY_ID}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Remove selected repository from an organization secret [DELETE]
DELETE {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dependabot/secrets/{{$dotenv SECRET_NAME}}/repositories/{{$dotenv REPOSITORY_ID}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List Dependabot alerts for a repository [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/alerts?page={{$dotenv PAGE}}&per_page={{$dotenv PER_PAGE}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get a Dependabot alert [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/alerts/{{$dotenv ALERT_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Update a Dependabot alert [PATCH]
PATCH {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/alerts/{{$dotenv ALERT_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### List repository secrets [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/secrets
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get a repository public key [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/secrets/public-key
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get a repository secret [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/secrets/{{$dotenv SECRET_NAME}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Create or update a repository secret [PUT]
PUT {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/secrets/{{$dotenv SECRET_NAME}}
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### Delete a repository secret [DELETE]
DELETE {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dependabot/secrets/{{$dotenv SECRET_NAME}}
Authorization: Bearer {{$dotenv GH_TOKEN}}