# Requests for tag: secret-scanning



### List secret scanning alerts for an enterprise [GET]
GET {{$dotenv BASE_URL}}/enterprises/{{$dotenv ENTERPRISE_NAME}}/secret-scanning/alerts
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List bypass requests for secret scanning for an org [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/bypass-requests/secret-scanning
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List alert dismissal requests for secret scanning for an org [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/dismissal-requests/secret-scanning
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List secret scanning alerts for an organization [GET]
GET {{$dotenv BASE_URL}}/orgs/{{$dotenv ORG_NAME}}/secret-scanning/alerts
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List bypass requests for secret scanning for a repository [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/bypass-requests/secret-scanning
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get a bypass request for secret scanning [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/bypass-requests/secret-scanning/{{$dotenv BYPASS_REQUEST_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Review a bypass request for secret scanning [PATCH]
PATCH {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/bypass-requests/secret-scanning/{{$dotenv BYPASS_REQUEST_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### Dismiss a response on a bypass request for secret scanning [DELETE]
DELETE {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/bypass-responses/secret-scanning/{{$dotenv BYPASS_RESPONSE_ID}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### List alert dismissal requests for secret scanning for a repository [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dismissal-requests/secret-scanning
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get an alert dismissal request for secret scanning [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dismissal-requests/secret-scanning/{{$dotenv ALERT_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Review an alert dismissal request for secret scanning [PATCH]
PATCH {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/dismissal-requests/secret-scanning/{{$dotenv ALERT_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### List secret scanning alerts for a repository [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/secret-scanning/alerts
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Get a secret scanning alert [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/secret-scanning/alerts/{{$dotenv ALERT_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Update a secret scanning alert [PATCH]
PATCH {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/secret-scanning/alerts/{{$dotenv ALERT_NUMBER}}
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### List locations for a secret scanning alert [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/secret-scanning/alerts/{{$dotenv ALERT_NUMBER}}/locations
Authorization: Bearer {{$dotenv GH_TOKEN}}

### Create a push protection bypass [POST]
POST {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/secret-scanning/push-protection-bypasses
Authorization: Bearer {{$dotenv GH_TOKEN}}
Content-Type: application/json
{}

### Get secret scanning scan history for a repository [GET]
GET {{$dotenv BASE_URL}}/repos/{{$dotenv OWNER}}/{{$dotenv REPO}}/secret-scanning/scan-history
Authorization: Bearer {{$dotenv GH_TOKEN}}